language: rust
rust:
- stable
- beta
- nightly
env:
- RUSTYASM_FEATURES=""
- RUSTYASM_FEATURES="proc-macro"
matrix:
  allow_failures:
  - rust: stable
  - rust: beta

cache: cargo
sudo: required

before_cache: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin
  fi

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID --features "$RUSTYASM_FEATURES"
  fi

addons:
  apt:
    packages:
    - libssl-dev

script:
- cargo clean
- cargo build --features "$RUSTYASM_FEATURES"
- cargo test --features "$RUSTYASM_FEATURES"
- cargo bench --features "$RUSTYASM_FEATURES"
- cargo doc --features "$RUSTYASM_FEATURES"
- cargo test --features "$RUSTYASM_FEATURES" --release

fast_finish: true
